{
 "title": "Revenue Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Store Revenue Table",
   "type": "table",
   "description": "Show all store revenue values",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "ecommerce_revenue_by_store", "legendFormat": "{{store_name}}" }
   ]
  },
  {
   "title": "Top 10 Revenue Stores",
   "type": "piechart",
   "description": "Group by store_name",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ecommerce_revenue_by_store)",
     "legendFormat": "{{store_name}}"
    }
   ]
  },
  {
   "title": "Product Revenue Table",
   "type": "table",
   "description": "\tColumns: product_name, product_id, value",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ecommerce_revenue_by_product",
     "legendFormat": "{{product_name}} ({{product_id}})"
    }
   ]
  },
  {
   "title": "Top 10 Revenue Products",
   "type": "barchart",
   "description": "Group by product_name",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10, ecommerce_revenue_by_product)",
     "legendFormat": "{{product_name}} ({{product_id}}) "
    }
   ]
  }
 ]
}