{
 "title": "Eccomerce overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Quantity Sold",
   "type": "stat",
   "description": "\tAll units sold",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Items" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecommerce_sales_total_quantity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Sales Records",
   "type": "stat",
   "description": "Number of sales rows",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecommerce_sales_rows\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecommerce_revenue_total" }
   ]
  }
 ]
}